### ISSUE TITLE
Opdracht 1.2

### ISSUE THREAD

**Issue by pp-koch** [WesselSmit/browser-technologies-1920#1]
* een beschrijving van alle features die je hebt getest

	Goed
	
* een beschrijving van de Devices en browsers waar je op hebt getest

	Goed.

* een beschrijving van de screenreader test

	Maak er <html lang="nl"> van in plaats van "en" en probeer opnieuw.

* beschrijf hoe je de problemen hebt opgelost, of hoe je dit zou oplossen (met todo’s) als je genoeg tijd en budget zou hebben

	Goed.

**Comment by WesselSmit** [comment]
>Maak er van in plaats van "en" en probeer opnieuw.

Ik weet dat ik dit nog even goed moet gaan doen, maar ik begrijp niet helemaal wat je bedoelt met `Maak er van in plaats van "en"`.

**Comment by pp-koch** [comment]
Ah, HTML wordt gestript.

html lang="en" is de boosdoener. Verander in html lang="nl" en de screenreader werkt.

**Comment by WesselSmit** [comment]
Hierbij mijn 2e poging met de screenreader, ik heb mijn bevindingen hieronder gezet maar dit valt natuurlijk ook terug te lezen in mijn readme.

## Screenreader

Ik heb in de HTML het `lang` attribuut van **en** verandert naar **nl** zodat de nederlandee content ook voorgelezen word door een nederlandse stem. 

De overviewpagina is uitleesbaar, wel erg vervelend dat de elementen uitgelezen worden; zo krijg je elke keer te horen “heading level 4” etc. 

Ik weet niet of de mensen die screenreaders gebruiken het interessant vinden om te horen wat voor element de focus heeft maar als dat niet belangrijk is dan kan je dit misschien voorkomen door er een “aria” attribuut op te zetten.
Aan de andere kant kan ik me ook wel weer voorstellen dat mensen die screenreaders gebruiken willen weten dat het een titel of iets dergelijk is (blinde mensen).

Wanneer je letterlijk op de `<a>` hoverde werd alle content voorgelezen (wat de bedoeling is), maar als je over een van de child-nodes hoverde dan word alleen dat element voorgelezen. Met `tab` werkt dit dus erg goed, maar met de muis minder. Een manier om dit probleem te voorkomen kan misschoen `pointer-events: none` zijn. Op deze manier werkt de link nogsteeds en is alle content leesbaar terwijl het element geen hover-state heeft en dus niet een screenreader kan trigerren.

Verder viel het me op dat als in een `<a>` een `<h4>`, `<p>` & `<p>` bevat dat er geen pauzes tussen de elementen zitten. Er word rechtstreeks van element naar element gegaan; ik kan me voorstellen dat als je dit dagelijks gebruikt dat dit geen probleem is. Maar voor de personen bij wie het wel een probleem is valt dit probleem te verhelpen; er moeten `.` achter de zinnen gezet worden zodat de screenreader een korte pauze neemt tussen de zinnen.


De profielpagina werkt ook normaal, echter kan ik de `<input>` niet laten voorlezen door de screenreader, dit zo mogelijk zijn met `aria-label`.

**Comment by pp-koch** [comment]
Prima; bedankt. Je hebt deze opdracht gehaald.
